version: '3.9'

volumes:
  pgdata:

networks:
  backend:

services:

  db:
    image: postgres:14.3-alpine3.15
    ports:
      - "5431:5432"
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: advertisement
    volumes:
      - ./log:/var/log
      - .:/docker-entrypoint-initdb.d
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  app_aiohttp:
    build: .
    depends_on:
      - db
    networks:
      - backend
    command: python server.py
    ports:
      - "8080:8080"